// Generated by CoffeeScript 1.4.0
var CodeView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CodeView = (function(_super) {

  __extends(CodeView, _super);

  function CodeView(site_item, el) {
    this.site_item = site_item;
    this.el = el;
    CodeView.__super__.constructor.call(this, this.site_item);
    this.pre = new_dom_element({
      parentNode: this.el,
      nodeName: "pre",
      className: this.site_item.type,
      txt: this.site_item.txt,
      style: {
        fontSize: "10px",
        background: "#d9e0e7"
      }
    });
    hljs.highlightBlock(this.pre);
  }

  return CodeView;

})(Process);
