// Generated by CoffeeScript 1.4.0
var IFrameView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

IFrameView = (function(_super) {

  __extends(IFrameView, _super);

  function IFrameView(site_item, el) {
    var fa_collapse, fa_expand, panel_title;
    this.site_item = site_item;
    this.el = el;
    IFrameView.__super__.constructor.call(this, this.site_item);
    this.panel_inverse = new_dom_element({
      parentNode: this.el,
      className: "panel panel-inverse"
    });
    this.panel_heading = new_dom_element({
      parentNode: this.panel_inverse,
      className: "panel-heading"
    });
    this.panel_heading_btn = new_dom_element({
      parentNode: this.panel_heading,
      className: "panel-heading-btn"
    });
    this.expand = new_dom_element({
      parentNode: this.panel_heading_btn,
      nodeName: "a",
      className: "btn btn-xs btn-icon btn-circle btn-default",
      href: "javascript:;",
      dataclick: "panel-expand"
    });
    fa_expand = new_dom_element({
      parentNode: this.expand,
      nodeName: "i",
      className: "fa fa-expand"
    });
    this.collapse = new_dom_element({
      parentNode: this.panel_heading_btn,
      nodeName: "a",
      className: "btn btn-xs btn-icon btn-circle btn-warning",
      href: "javascript:;",
      dataclick: "panel-collapse"
    });
    fa_collapse = new_dom_element({
      parentNode: this.collapse,
      nodeName: "i",
      className: "fa fa-minus"
    });
    panel_title = new_dom_element({
      parentNode: this.panel_heading,
      nodeName: "h2",
      className: "panel-title",
      txt: this.site_item.title.get()
    });
    if (this.site_item.format.get() === "page-height") {
      this.window_height = document.body.clientHeight - 180;
      this.panel_content = new_dom_element({
        id: this.site_item.id.get(),
        parentNode: this.panel_inverse,
        className: "embed-responsive",
        style: {
          height: this.window_height + "px"
        }
      });
    } else if (this.site_item.format.get() === "16by9") {
      this.panel_content = new_dom_element({
        id: this.site_item.id.get(),
        parentNode: this.panel_inverse,
        className: "embed-responsive embed-responsive-16by9"
      });
    }
    this.iframe = new_dom_element({
      nodeName: "iframe",
      className: "embed-responsive-item",
      parentNode: this.panel_content,
      src: this.site_item.src
    });
  }

  return IFrameView;

})(Process);
