// Generated by CoffeeScript 1.4.0
var ImageView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ImageView = (function(_super) {

  __extends(ImageView, _super);

  function ImageView(site_item, el) {
    this.site_item = site_item;
    this.el = el;
    ImageView.__super__.constructor.call(this, this.site_item);
    this.img = new_dom_element({
      nodeName: "img",
      className: "img-responsive",
      parentNode: this.el,
      src: this.site_item.src,
      style: {
        width: this.site_item.width,
        margin: "auto"
      }
    });
  }

  return ImageView;

})(Process);
