// Generated by CoffeeScript 1.4.0
var PanelView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PanelView = (function(_super) {

  __extends(PanelView, _super);

  function PanelView(site_item, el) {
    var fa_collapse, fa_expand, panel_content, panel_title;
    this.site_item = site_item;
    this.el = el;
    PanelView.__super__.constructor.call(this, this.site_item);
    this.panel_inverse = new_dom_element({
      parentNode: this.el,
      className: "panel panel-inverse",
      id: this.site_item.balise
    });
    this.panel_heading = new_dom_element({
      parentNode: this.panel_inverse,
      className: "panel-heading"
    });
    this.panel_heading_btn = new_dom_element({
      parentNode: this.panel_heading,
      className: "panel-heading-btn"
    });
    this.expand = new_dom_element({
      parentNode: this.panel_heading_btn,
      nodeName: "a",
      className: "btn btn-xs btn-icon btn-circle btn-default",
      href: "javascript:;",
      dataclick: "panel-expand"
    });
    fa_expand = new_dom_element({
      parentNode: this.expand,
      nodeName: "i",
      className: "fa fa-expand"
    });
    this.collapse = new_dom_element({
      parentNode: this.panel_heading_btn,
      nodeName: "a",
      className: "btn btn-xs btn-icon btn-circle btn-warning",
      href: "javascript:;",
      dataclick: "panel-collapse"
    });
    fa_collapse = new_dom_element({
      parentNode: this.collapse,
      nodeName: "i",
      className: "fa fa-minus"
    });
    panel_title = new_dom_element({
      parentNode: this.panel_heading,
      nodeName: "h2",
      className: "panel-title",
      txt: this.site_item.title.get()
    });
    panel_content = new_dom_element({
      id: this.site_item.id.get(),
      parentNode: this.panel_inverse,
      className: "panel-body"
    });
  }

  return PanelView;

})(Process);
