// Generated by CoffeeScript 1.4.0
var ParagraphView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ParagraphView = (function(_super) {

  __extends(ParagraphView, _super);

  function ParagraphView(site_item, el) {
    this.site_item = site_item;
    this.el = el;
    ParagraphView.__super__.constructor.call(this, this.site_item);
    this.p = new_dom_element({
      nodeName: "p",
      parentNode: this.el,
      txt: this.site_item.txt.get()
    });
  }

  return ParagraphView;

})(Process);
