// Generated by CoffeeScript 1.4.0
var RowView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RowView = (function(_super) {

  __extends(RowView, _super);

  function RowView(site_item, el) {
    this.site_item = site_item;
    this.el = el;
    RowView.__super__.constructor.call(this, this.site_item);
    this.section = new_dom_element({
      parentNode: this.el,
      nodeName: "section",
      datascrollview: "true"
    });
    this.row = new_dom_element({
      parentNode: this.section,
      className: "row",
      id: this.site_item.id.get()
    });
  }

  return RowView;

})(Process);
