// Generated by CoffeeScript 1.4.0
var TableView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TableView = (function(_super) {

  __extends(TableView, _super);

  function TableView(site_item, el) {
    var i, j, _i, _j, _ref, _ref1;
    this.site_item = site_item;
    this.el = el;
    TableView.__super__.constructor.call(this, this.site_item);
    this.table = new_dom_element({
      nodeName: "table",
      className: "table",
      parentNode: this.el
    });
    this.thead = new_dom_element({
      nodeName: "thead",
      parentNode: this.table
    });
    for (i = _i = 0, _ref = this.site_item.lst.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      this.tr = new_dom_element({
        nodeName: "tr",
        parentNode: this.thead
      });
      for (j = _j = 0, _ref1 = this.site_item.lst[i].length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
        this.td = new_dom_element({
          nodeName: "td",
          parentNode: this.tr,
          txt: this.site_item.lst[i][j],
          style: {
            verticalAlign: "middle"
          }
        });
      }
    }
  }

  return TableView;

})(Process);
