#!/bin/bash

Start() 
{
if ps ax | grep -v grep | grep -v grep | grep "./spinalhub -b ../browser-organ/ -p 8888 -P 8889 -q 8890" > /dev/null
then
    echo "Spinalhub is already running!"
else
    echo "Running..."
    cd ./nerve-center; 
    make & 
    sleep 1;
    cd ../organs-manager; 
    ./run & 
fi
}

Stop()
{
echo "Stoping..."
pkill -f "./spinalhub -b ../browser-organ/ -p 8888 -P 8889 -q 8890";
}

if [[ $1 == "stop" ]]; then Stop
else 
    Start
fi