class CastemTrussPGDDemoItem extends TreeItem
    constructor: (name = 'Truss PGD')->
        super()
                
        @_name.set name
        
        @add_attr
            edited_by : 'LMT'
            stamp: "img/CastemTrussPGD.png"
            txt: "Castem PGD : Truss (LMT)"
            demo_app : "CastemTrussPGDDemoItem"
            directory : "CastemTrussPGD"
            video_link : undefined
            publication_link : "http://resources.is-sim.com/Louf_Champaney_FINEL.pdf"

    associated_application: ()->
        apps = new Lst
        apps.push new TreeAppApplication_CastemTruss
        return apps
    
    run_demo : (app_data)->
        app = new TreeAppApplication
        a = app.add_item_depending_selected_tree app_data, CastemTrussPGDItem, (object) =>
            app_data.watch_item object._children[0]
            app_data.watch_item object._children[0]._children[0]
            app_data.watch_item object._children[0]._children[1]
            app_data.watch_item object._children[0]._children[2]
        
    read_me: ( c ) ->
        c.panel "col2", "rm", "Read me", "readme"
        c.heading "rm", 5, "Application"
        c.paragraph "rm", "
        This application is an example of the PGD reduction method presented in the paper beside, in the section <b>\"4: First application to a simple structure\"</b>. See this
        part for more information.<br>
        In the application, you can change all the paremeters of the example (geometry, materials, PGD). When they are set up, you just have to click a button to run the
        Castem algorithm.<br>
        Here is the diagram of the structure (introduced in the paper):
        "
        c.image "rm", "img/truss_fig.png", "300px"
        c.heading "rm", 5, "Interface"
        c.paragraph "rm", "
        The application <b>Castem PGD</b> is already included in the <b>Scene</b>, under the <b>Session</b> model. You can include more instances of this application by clicking the 
        <b>Apps</b> button then the blue button.<br>
        The main model of this app contains 2 children: <b>Truss</b> and <b>Strained Truss</b>. The Truss item also has 4 children, representing the 3 beams of the structure and
        the model that contains the PGD parameters. You can display these models (except the PGD paremeters) by clicking the eye icon next to them.
        In the 3D window, you can manipulate the camera by using the left click, the scroll wheel or the icons on the top of the window.<br>
        In the Scene panel, click the models to display their attributes in the <b>Inspector</b> panel below. Modifying these attributes will change the models and their 
        visualization. The attributes are:
        <ul>
        <li><b>Castem PGD</b>: the name of the result text file generated by the Castem algorithm;</li>
        <li><b>Truss</b>: paremeters of the whole structure (geometry, boundary conditions);</li>
        <li><b>Beams</b>: materials and PGD parameters of each beam;</li>
        <li><b>PGD parameters</b>: general parameters of the PGD method;</li>
        <li><b>Strained Truss</b>: Results of the algorithm: displacement of the point D, a warp factor for the visualization and sliders to act on the results (see the paper for
        more information about the K variables).</li>
        </ul>
        "        
        c.heading "rm", 5, "Usage"
        c.paragraph "rm", "
        IMPORTANT: You need Cast3m on you computer to run the algorithm: see the <a href=http://www-cast3m.cea.fr/ target=_blank >Cast3m site</a>.<br><br>
        At the launch of this demo, you should see in the 3D panel the original structure: the beams represented by white lines and the points represented by green circles.<br>
        The application usage is composed of three steps: defining the parameters, running the Castem algorithm and visualizing the results in the 3D window. 
        <ol>
        <li>Click the <b>Truss</b> item in the <b>Scene</b> panel to display its attributes in the <b>Inspector</b> panel. Then enter values in the input fields.</li>
        <li>Do the same for the <b>Beam</b> and <b>PGD Parameters</b> items.</li>
        <li>Click the <b>Castem PGD</b> item in the Scene panel then click the Play button in the contextual bar to the left or next to the item in the Scene panel.</li>
        <li>Wait until the application ends. You should see alerts at the top of the 3D window when it is done (\"Castem computation finished\", \"Psi/lambda storage finished\").</li>
        <li>Click the <b>Strained Truss</b> item in the Scene panel. Display it by clicking the eye icon next to it. The strained structure is displayed in red in the 3D
        window (as the original structure is in white).</li>
        <li>Move the sliders K1, K2 and K3 to update the position of the point D. As the values are quite low, increase the warp factor to see better. Moving the sliders draws
        the positions of the point D during the variations of the K parameters. To erase these drawings, just change the warp factor.</li>
        </ol>
        "
