class Castem2DPGDDemoItem extends TreeItem
    constructor: (name = '2D PGD')->
        super()
                
        @_name.set name
        
        @add_attr
            edited_by : 'LMT'
            stamp: "img/Castem2DPGD.png"
            txt: "Castem PGD : 2D (LMT)"
            demo_app : "Castem2DPGDDemoItem"
            directory : "Castem2DPGD"
            video_link : undefined
            publication_link : "http://resources.is-sim.com/Louf_Champaney_FINEL.pdf"

    associated_application: ()->
        apps = new Lst
        apps.push new TreeAppApplication_Castem2D
        return apps
    
    run_demo : (app_data)->
        app = new TreeAppApplication
        a = app.add_item_depending_selected_tree app_data, Castem2DPGDItem
        
    read_me: ( c ) ->
        c.panel "col2", "rm", "Read me", "readme"
        c.heading "rm", 5, "Application"
        c.paragraph "rm", "
        This application is an example of the PGD reduction method presented in the paper beside, in the section <b>\"5: Application to a complex structure\"</b>. See this
        part for more information.<br>
        In the application, you can change all the paremeters of the example (geometry, materials, PGD). When they are set up, you just have to click a button to run the
        Castem algorithm.<br>
        Here is the diagram of the structure (introduced in the paper):
        "
        c.image "rm", "img/2d_fig.png", "300px"
        c.heading "rm", 5, "Interface"
        c.paragraph "rm", "
        The application <b>Castem PGD</b> is already included in the <b>Scene</b>, under the <b>Session</b> model. You can include more instances of this application by clicking the 
        <b>Apps</b> button then the blue button.<br>
        The main model of this app contains 2 children: <b>Assembly</b> and <b>Strained Assembly</b>. The Assembly item also has 6 children, representing the 3 solids of the 
        structure, the 2 glues and a model that contains the PGD parameters. You can display these models (except the glues and the PGD paremeters) by clicking the eye icon 
        next to them. In the 3D window, you can manipulate the camera by using the left click, the scroll wheel or the icons on the top of the window.<br>
        In the Scene panel, click the models to display their attributes in the <b>Inspector</b> panel below. Modifying these attributes will change the models and their 
        visualization. The attributes are:
        <ul>
        <li><b>Castem PGD</b>: the name of the result text file generated by the Castem algorithm;</li>
        <li><b>Assembly</b>: paremeters of the whole structure (geometry, boundary conditions);</li>
        <li><b>Solids</b> and <b>Glues</b>: materials and PGD parameters of each solid and glue;</li>
        <li><b>PGD parameters</b>: general parameters of the PGD method;</li>
        <li><b>Strained Assembly</b>: Results of the algorithm: a fields set of the position of each node of the structure, a warp factor for the visualization and sliders to act on the results (see the paper for
        more information about the K variables).</li>
        </ul>
        "        
        c.heading "rm", 5, "Usage"
        c.paragraph "rm", "
        IMPORTANT: You need Cast3m on you computer to run the algorithm: see the <a href=http://www-cast3m.cea.fr/ target=_blank >Cast3m site</a>.<br><br>
        At the launch of this demo, you shouldn't see anything the 3D window: as the mesh is built in the Castem algorithm, you have to run it once to display the structure.<br>
        The application usage is composed of three steps: defining the parameters, running the Castem algorithm and visualizing the results in the 3D window. 
        <ol>
        <li>Click the <b>Assembly</b> item in the <b>Scene</b> panel to display its attributes in the <b>Inspector</b> panel. Then enter values in the input fields.</li>
        <li>Do the same for the <b>Solid</b>, <b>Glue</b> and <b>PGD Parameters</b> items.</li>
        <li>Click the <b>Castem PGD</b> item in the Scene panel then click the Play button in the contextual bar to the left or next to the item in the Scene panel.</li>
        <li>Wait until the application ends. You should see alerts at the top of the 3D window when it is done (\"Castem computation finished\", \"Meshes creation finished\",
        \"Psi/lambda storage finished\").</li>
        <li>Now that the mesh of the original structure is built, you can display it in the 3D window. To do so, click the eye icons next to Assembly to see the whole structure,
        or next to a Solid item to see a part of it only. You probably need to fit the camera to the view by clicking the \"Fit object to the view\" icon at the top of the 3D
        window (keyboard shortcut: F).</li>
        <li>Click the <b>Strained Assembly</b> item in the Scene panel. Display it by clicking the eye icon next to it (hide the original assembly to not overload the window). 
        You should see the field representing the X position of each node of the mesh.</li>
        <li>The field options are in the Inspector panel, under the <b>Field set</b> attribute, especially the field you want to display (Y position instead of X, for example).</li>
        <li>Move one of the sliders <b>K</b> to update the nodes positions of the mesh and the field values. As the values are quite low, increase the warp factor to see better.</li>
        </ol>
        "