// Generated by CoffeeScript 1.4.0
var ColView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ColView = (function(_super) {

  __extends(ColView, _super);

  function ColView(site_item, el) {
    this.site_item = site_item;
    this.el = el;
    ColView.__super__.constructor.call(this, this.site_item);
    this.width = "col-lg-" + this.site_item.width.get();
    this.col = new_dom_element({
      parentNode: this.el,
      className: this.width,
      id: this.site_item.id
    });
  }

  return ColView;

})(Process);
